export const blog = [
  {
    id: 1,
    title: "Cooking tips make cooking simple",
    desc: "Sed quia non numquam modi tempora indunt ut labore et dolore magnam aliquam quaerat",
    date: "May 4, 2019",
    Comment: 5,
    img: "/assets/img/blog/blog-1.jpg",
  },
  {
    id: 2,
    title: "Cooking tips make cooking simple",
    desc: "Sed quia non numquam modi tempora indunt ut labore et dolore magnam aliquam quaerat",
    date: "May 4, 2019",
    Comment: 5,
    img: "/assets/img/blog/blog-2.jpg",
  },
  {
    id: 3,
    title: "Cooking tips make cooking simple",
    desc: "Sed quia non numquam modi tempora indunt ut labore et dolore magnam aliquam quaerat",
    date: "May 4, 2019",
    Comment: 5,
    img: "/assets/img/blog/blog-3.jpg",
  },
];
export const blogPage = [
  {
    id: 1,
    title: "Cooking tips make cooking simple",
    desc: "Sed quia non numquam modi tempora indunt ut labore et dolore magnam aliquam quaerat",
    date: "May 4, 2019",
    Comment: 5,
    img: "/assets/img/blog/blog-1.jpg",
  },
  {
    id: 2,
    title: "Cooking tips make cooking simple",
    desc: "Sed quia non numquam modi tempora indunt ut labore et dolore magnam aliquam quaerat",
    date: "May 4, 2019",
    Comment: 5,
    img: "/assets/img/blog/blog-2.jpg",
  },
  {
    id: 3,
    title: "Cooking tips make cooking simple",
    desc: "Sed quia non numquam modi tempora indunt ut labore et dolore magnam aliquam quaerat",
    date: "May 4, 2019",
    Comment: 5,
    img: "/assets/img/blog/blog-3.jpg",
  },
  {
    id: 4,
    title: "Cooking tips make cooking simple",
    desc: "Sed quia non numquam modi tempora indunt ut labore et dolore magnam aliquam quaerat",
    date: "May 4, 2019",
    Comment: 5,
    img: "/assets/img/blog/blog-4.jpg",
  },
  {
    id: 5,
    title: "Cooking tips make cooking simple",
    desc: "Sed quia non numquam modi tempora indunt ut labore et dolore magnam aliquam quaerat",
    date: "May 4, 2019",
    Comment: 5,
    img: "/assets/img/blog/blog-5.jpg",
  },
  {
    id: 6,
    title: "Cooking tips make cooking simple",
    desc: "Sed quia non numquam modi tempora indunt ut labore et dolore magnam aliquam quaerat",
    date: "May 4, 2019",
    Comment: 5,
    img: "/assets/img/blog/blog-6.jpg",
  },
];
